"""add_face_biometric_fields

Revision ID: 5708e329289b
Revises: b7463634f7cc
Create Date: 2025-09-29 22:05:08.020603

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5708e329289b"
down_revision = "b7463634f7cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("face_embedding_encrypted", sa.Text(), nullable=True)
    )
    op.add_column("users", sa.Column("face_enrollment_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("face_enrolled", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("face_enrollment_quality", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "face_enrollment_quality")
    op.drop_column("users", "face_enrolled")
    op.drop_column("users", "face_enrollment_id")
    op.drop_column("users", "face_embedding_encrypted")
    # ### end Alembic commands ###
